const DummyData = [
  {
    trainId: "Udarata Menike",
    latitude: 7.2906,
    longitude: 80.6337,
    locationName: "Kandy",
    timestamp: new Date(),
  },
  {
    trainId: "Yal Devi",
    latitude: 9.6615,
    longitude: 80.0255,
    locationName: "Jaffna",
    timestamp: new Date(),
  },
  {
    trainId: "Podi Menike",
    latitude: 6.9271,
    longitude: 79.8612,
    locationName: "Colombo",
    timestamp: new Date(),
  },
  {
    trainId: "Rajarata Rajina",
    latitude: 8.3114,
    longitude: 80.4037,
    locationName: "Anuradhapura",
    timestamp: new Date(),
  },
  {
    trainId: "Uttara Devi",
    latitude: 7.8731,
    longitude: 80.7718,
    locationName: "Kurunegala",
    timestamp: new Date(),
  },
  {
    trainId: "Sagarika",
    latitude: 6.0535,
    longitude: 80.221,
    locationName: "Matara",
    timestamp: new Date(),
  },
  {
    trainId: "Meenagaya",
    latitude: 7.8731,
    longitude: 80.7718,
    locationName: "Kurunegala",
    timestamp: new Date(),
  },
  {
    trainId: "Samudra Devi",
    latitude: 6.9271,
    longitude: 79.8612,
    locationName: "Colombo",
    timestamp: new Date(),
  },
  {
    trainId: "Dakshina Intercity",
    latitude: 6.0535,
    longitude: 80.221,
    locationName: "Matara",
    timestamp: new Date(),
  },
  {
    trainId: "Ruhunu Kumari",
    latitude: 6.9271,
    longitude: 79.8612,
    locationName: "Colombo",
    timestamp: new Date(),
  },
  {
    trainId: "Gal Oya",
    latitude: 7.3021,
    longitude: 81.6745,
    locationName: "Batticaloa",
    timestamp: new Date(),
  },
  {
    trainId: "Pulathisi",
    latitude: 8.3445,
    longitude: 81.0545,
    locationName: "Polonnaruwa",
    timestamp: new Date(),
  },
  {
    trainId: "Rajarata Rejina",
    latitude: 8.3114,
    longitude: 80.4037,
    locationName: "Anuradhapura",
    timestamp: new Date(),
  },
  {
    trainId: "Kankesanthurai Express",
    latitude: 9.8167,
    longitude: 80.0325,
    locationName: "Kankesanthurai",
    timestamp: new Date(),
  },
  {
    trainId: "Mannar Line",
    latitude: 8.9783,
    longitude: 79.9044,
    locationName: "Mannar",
    timestamp: new Date(),
  },
  {
    trainId: "Trincomalee Express",
    latitude: 8.5874,
    longitude: 81.2152,
    locationName: "Trincomalee",
    timestamp: new Date(),
  },
  {
    trainId: "Vavuniya Express",
    latitude: 8.7514,
    longitude: 80.4976,
    locationName: "Vavuniya",
    timestamp: new Date(),
  },
  {
    trainId: "Badulla Express",
    latitude: 6.9896,
    longitude: 81.055,
    locationName: "Badulla",
    timestamp: new Date(),
  },
  {
    trainId: "Galle Express",
    latitude: 6.0535,
    longitude: 80.221,
    locationName: "Galle",
    timestamp: new Date(),
  },
  {
    trainId: "Panadura Express",
    latitude: 6.7136,
    longitude: 79.9071,
    locationName: "Panadura",
    timestamp: new Date(),
  },
];

module.exports = DummyData;
